- name: Setup development environment
  hosts: localhost
  become: yes

  vars_files:
    - vars.yml

  vars:
    nginx_port: 8082
    laravel_directory: /var/www/laravel
    vue_directory: /var/www/vue
    ansible_python_interpreter: /usr/bin/python3
    php_version: "8.1"
    node_version: "16"

  tasks:
    - include_tasks: tasks/general_install.yml
    - include_tasks: tasks/nginx.yml

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - debconf-utils
        - python3-mysqldb
        - nodejs
        - npm

    - name: Install Node.js version manager (nvm)
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        executable: /bin/bash

    - name: Install specific version of Node.js
      shell: |
        source ~/.nvm/nvm.sh
        nvm install {{ node_version }}
      args:
        executable: /bin/bash
      environment:
        NVM_DIR: "/home/{{ ansible_facts['user'] | default('ubuntu') }}/.nvm"

    - name: Set MySQL root password for installation
      ansible.builtin.shell: |
        echo "mysql-server mysql-server/root_password password {{ mysql_root_password }}" | debconf-set-selections
        echo "mysql-server mysql-server/root_password_again password {{ mysql_root_password }}" | debconf-set-selections

    - name: Install MySQL server
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Run mysql_secure_installation equivalent
      ansible.builtin.command: |
        mysql -u root -p'{{ mysql_root_password }}' -e "DELETE FROM mysql.user WHERE User=''; FLUSH PRIVILEGES;"

    - name: Create MySQL database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user with privileges
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: "localhost"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Delete /var/www/laravel and /var/www/vue directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/laravel
        - /var/www/vue

    - name: Install Composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: '0755'

    - name: Run Composer Installer
      command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: Clone Laravel repository
      git:
        repo: 'https://github.com/qfranklin/laravel.git'
        dest: "{{ laravel_directory }}"
        version: main

    - name: Clone Vue repository
      git:
        repo: 'https://github.com/qfranklin/vue.git'
        dest: "{{ vue_directory }}"
        version: main

    - name: Install Laravel dependencies with Composer
      command: composer install
      args:
        chdir: "{{ laravel_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
        COMPOSER_ALLOW_SUPERUSER: "1"

    - name: Install NPM dependencies for Vue
      command: npm install
      args:
        chdir: "{{ vue_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    - name: Configure Laravel .env
      template:
        src: env.j2
        dest: "{{ laravel_directory }}/.env"
        mode: '0644'
      notify: Generate Laravel app key

    - name: Generate Laravel app key
      command: php artisan key:generate
      args:
        chdir: "{{ laravel_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    - name: Run Laravel migrations
      command: php artisan migrate
      args:
        chdir: "{{ laravel_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    - name: Ensure the www-data group exists
      ansible.builtin.group:
        name: www-data
        state: present

    - name: Ensure the www-data user exists
      ansible.builtin.user:
        name: www-data
        group: www-data
        shell: /usr/sbin/nologin
        state: present
        system: yes

    - name: Set ownership for Laravel directories
      file:
        path: /var/www/laravel
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions for storage and bootstrap/cache directories
      file:
        path: "{{ item }}"
        mode: '775'
        recurse: yes
      loop:
        - /var/www/laravel/storage
        - /var/www/laravel/bootstrap/cache

    - name: Set ownership for Vue directory
      file:
        path: "{{ vue_directory }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions for Vue directory
      file:
        path: "{{ vue_directory }}"
        mode: '755'
        recurse: yes

    # Build the Vue application for production
    - name: Build Vue application for production
      command: npm run build
      args:
        chdir: "{{ vue_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    # Configure Nginx to serve the Vue application
    - name: Configure Nginx for Vue application
      ansible.builtin.blockinfile:
        path: /etc/nginx/sites-available/default
        block: |
          server {
              listen 8080;
              server_name yourdomain.com;

              location / {
                  root {{ vue_directory }}/dist;
                  try_files $uri $uri/ /index.html;
              }
          }

  handlers:
    - name: Generate Laravel app key
      command: php artisan key:generate
      args:
        chdir: "{{ laravel_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
