- name: Setup environment
  hosts: all
  become: yes

  vars_files:
    - "vars/{{ inventory_file | basename | splitext | first }}.yml"

  vars:
    nginx_port: "{{ nginx_port_var }}"
    laravel_directory: /var/www/laravel
    vue_directory: /var/www/vue
    ansible_python_interpreter: /usr/bin/python3
    php_version: "8.1"
    node_version: "18"

  pre_tasks:
    - name: Setup development tools
      become: no
      become_user: "{{ ansible_user_id }}"
      when: inventory_file | basename | splitext | first == "dev"
      block:
        - name: Configure Git
          git_config:
            name: "{{ item.name }}"
            scope: global
            value: "{{ item.value }}"
          loop:
            - { name: 'user.email', value: '{{ git_email }}' }
            - { name: 'user.name', value: '{{ git_name }}' }

  tasks:
    - include_tasks: tasks/general_install.yml
    - include_tasks: tasks/nodejs.yml
    - include_tasks: tasks/mysql.yml
    - include_tasks: tasks/laravel.yml
    - include_tasks: tasks/vue.yml
    - include_tasks: tasks/php_config.yml
    - name: Restart PHP-FPM service
      service:
        name: php8.1-fpm
        state: restarted
    - name: Wait for Vite server
      wait_for:
        port: 5173
        state: started
        timeout: 30
      when: inventory_file | basename | splitext | first == "dev"
    - include_tasks: tasks/nginx.yml