- name: Setup development environment
  hosts: localhost
  become: yes

  vars_files:
    - vars.yml

  vars:
    nginx_port: 8082
    laravel_directory: /var/www/laravel
    vue_directory: /var/www/vue
    ansible_python_interpreter: /usr/bin/python3
    php_version: "8.1"
    node_version: "16"

  tasks:
    - include_tasks: tasks/general_install.yml
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/mysql.yml
    - include_tasks: tasks/laravel.yml

    - name: Delete /var/www/laravel and /var/www/vue directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/laravel
        - /var/www/vue

    - name: Clone Vue repository
      git:
        repo: 'https://github.com/qfranklin/vue.git'
        dest: "{{ vue_directory }}"
        version: main

    - name: Install NPM dependencies for Vue
      command: npm install
      args:
        chdir: "{{ vue_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    - name: Ensure the www-data group exists
      ansible.builtin.group:
        name: www-data
        state: present

    - name: Ensure the www-data user exists
      ansible.builtin.user:
        name: www-data
        group: www-data
        shell: /usr/sbin/nologin
        state: present
        system: yes

    - name: Set ownership for Laravel directories
      file:
        path: /var/www/laravel
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions for storage and bootstrap/cache directories
      file:
        path: "{{ item }}"
        mode: '775'
        recurse: yes
      loop:
        - /var/www/laravel/storage
        - /var/www/laravel/bootstrap/cache

    - name: Set ownership for Vue directory
      file:
        path: "{{ vue_directory }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions for Vue directory
      file:
        path: "{{ vue_directory }}"
        mode: '755'
        recurse: yes

    # Build the Vue application for production
    - name: Build Vue application for production
      command: npm run build
      args:
        chdir: "{{ vue_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    # Configure Nginx to serve the Vue application
    - name: Configure Nginx for Vue application
      ansible.builtin.blockinfile:
        path: /etc/nginx/sites-available/default
        block: |
          server {
              listen 8080;
              server_name yourdomain.com;

              location / {
                  root {{ vue_directory }}/dist;
                  try_files $uri $uri/ /index.html;
              }
          }

  handlers:
    - name: Generate Laravel app key
      command: php artisan key:generate
      args:
        chdir: "{{ laravel_directory }}"
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
