- name: Delete Laravel directory
  file:
    path: "{{ laravel_directory }}"
    state: absent

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: '0755'

- name: Run Composer installer
  command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Clone Laravel repository
  git:
    repo: 'https://github.com/qfranklin/laravel.git'
    dest: "{{ laravel_directory }}"
    version: main

- name: Add /var/www/laravel as a safe directory for Git
  become: yes
  shell: git config --global --add safe.directory /var/www/laravel

- name: Configure Git to ignore file mode changes
  become: yes
  become_user: "{{ ansible_user_id }}"
  git_config:
    name: core.fileMode
    scope: local
    value: 'false'
    repo: "{{ laravel_directory }}"
  when: inventory_file | basename | splitext | first == "dev"

- name: Set ownership for Laravel directories
  file:
    path: "{{ laravel_directory }}"
    owner: www-data
    group: www-data
    recurse: yes
    mode: "{{ file_mode }}"

- name: Install Laravel dependencies with Composer
  become: yes
  become_user: www-data
  command: composer install --no-dev --no-interaction
  args:
    chdir: "{{ laravel_directory }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    HOME: "/var/www"

- name: Configure Laravel .env
  template:
    src: env.j2
    dest: "{{ laravel_directory }}/.env"
    mode: '0644'
    owner: www-data
    group: www-data

- name: Generate Laravel app key
  become: yes
  become_user: www-data
  become_method: sudo
  command: php artisan key:generate
  args:
    chdir: "{{ laravel_directory }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    HOME: "/var/www"

- name: Run Laravel migrations
  become: yes
  become_user: www-data
  become_method: sudo
  command: php artisan migrate
  args:
    chdir: "{{ laravel_directory }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    HOME: "/var/www"