- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Stop Nginx service
  service:
    name: nginx
    state: stopped

- name: Find the PHP-FPM socket path dynamically
  shell: "find /var/run/php -name 'php*-fpm.sock' | head -n 1"
  register: php_fpm_socket_path
  changed_when: false

- name: Configure Nginx for Vue and Laravel
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'

- name: Remove default symbolic link
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create symbolic link for Nginx config
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    force: yes

- name: Check Nginx configuration syntax
  command: nginx -t
  ignore_errors: yes
  register: nginx_config_check

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  when: nginx_config_check.rc == 0

- name: Reload Nginx to apply configuration changes
  service:
    name: nginx
    state: reloaded
  when: nginx_config_check.rc == 0