- name: Check for running Vite processes
  shell: |
    ps aux | grep "[v]ite"
  register: vite_check
  changed_when: false
  ignore_errors: yes

- name: Stop Vite processes if running
  shell: |
    pkill -f "node.*vite"
  when: vite_check.stdout != ""
  ignore_errors: yes

- name: Delete Vue directory
  file:
    path: "{{ vue_directory }}"
    state: absent

- name: Clone Vue repository
  git:
    repo: 'https://github.com/qfranklin/vue.git'
    dest: "{{ vue_directory }}"
    version: main

- name: Add /var/www/vue as a safe directory for Git
  become: yes
  shell: git config --global --add safe.directory /var/www/vue

- name: Configure Git to ignore file mode changes
  become: yes
  become_user: "{{ ansible_user_id }}"
  git_config:
    name: core.fileMode
    scope: local
    value: 'false'
    repo: "{{ vue_directory }}"
  when: inventory_file | basename | splitext | first == "dev"

- name: Create required directories for www-data
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  loop:
    - /var/www/.npm
    - /var/www/.cache
    - /var/www/.cache/Cypress

- name: Set ownership for Vue directory
  file:
    path: "{{ vue_directory }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Set permissions for Vue directory
  file:
    path: "{{ vue_directory }}"
    mode: "{{ file_mode }}"
    recurse: yes

- name: Install NPM dependencies for Vue
  become: yes
  become_user: www-data
  shell: |
    source /var/www/.nvm/nvm.sh
    npm install
  args:
    executable: /bin/bash
    chdir: "{{ vue_directory }}"
  environment:
    HOME: /var/www
    NVM_DIR: /var/www/.nvm

- name: Build Vue application
  become: yes
  become_user: www-data
  shell: |
    source /var/www/.nvm/nvm.sh
    nohup {{ npm_command }} > /var/www/vue/npm.log 2>&1 &
  args:
    executable: /bin/bash
    chdir: "{{ vue_directory }}"
  environment:
    HOME: /var/www
    NVM_DIR: /var/www/.nvm
    VITE_PORT: 5173
  async: 300 
  poll: 0