---
- name: Update apt packages
  apt:
    update_cache: yes

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - unzip
      - nginx
      - mysql-server
      - php
      - php-mysql
      - php-xml
      - php-mbstring
    state: present

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes